exynos/gpio: fix warning
These 'baseaddr' fields are storing I/O addresses, so it makes sense to
keep them wide enough to hold a proper pointer -- which also resolves
this warnings when we try to cast the I/O address to a struct:

../mosys-9999/drivers/samsung/gpio.c:84:9: error: cast to 'struct exynos_gpio_regs *' from smaller integer type 'uint32_t' (aka 'unsigned int') [-Werror,-Wint-to-pointer-cast]
        regs = (struct exynos_gpio_regs *)bank->baseaddr;
               ^

BUG=chromium:838349
TEST=build

Change-Id: I54356ac1fad87588043b81aea7da57db14fec63f
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1036359
Reviewed-by: Jason Clinton <jclinton@chromium.org>