Revert "mosys: Support mistral"
This reverts commit d633789123cc60a24d5252d1a479ac2edfa16442.

Reason for revert: Failed to compile. Please do not CHUMP CL.

Recent CQ:
https://cros-goldeneye.corp.google.com/chromeos/healthmonitoring/buildDetails?buildbucketId=8922842912147275488

mosys-1.2.3-r854: FAILED: mosys@sta/platform_mistral_memory.c.o 
mosys-1.2.3-r854: x86_64-pc-linux-gnu-clang  -Imosys@sta -I. -I../mosys-1.2.3 -I../mosys-1.2.3/include -I/usr/include/uuid -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -include config.h -std=gnu99 -Wno-address-of-packed-member -Wall -Werror -Wstrict-prototypes -Wundef -O2 -fPIC -MMD -MQ 'mosys@sta/platform_mistral_memory.c.o' -MF 'mosys@sta/platform_mistral_memory.c.o.d' -o 'mosys@sta/platform_mistral_memory.c.o' -c ../mosys-1.2.3/platform/mistral/memory.c
mosys-1.2.3-r854: ../mosys-1.2.3/platform/mistral/memory.c:120:19: error: use of undeclared identifier 'SAMSUNG_DDR3_1866_512M'; did you mean 'SAMSUNG_DDR3L_1866_512M'?
mosys-1.2.3-r854:                 memory_config = SAMSUNG_DDR3_1866_512M;
mosys-1.2.3-r854:                                 ^~~~~~~~~~~~~~~~~~~~~~
mosys-1.2.3-r854:                                 SAMSUNG_DDR3L_1866_512M
mosys-1.2.3-r854: ../mosys-1.2.3/platform/mistral/memory.c:52:2: note: 'SAMSUNG_DDR3L_1866_512M' declared here
mosys-1.2.3-r854:         SAMSUNG_DDR3L_1866_512M,
mosys-1.2.3-r854:         ^
mosys-1.2.3-r854: ../mosys-1.2.3/platform/mistral/memory.c:139:7: error: use of undeclared identifier 'SAMSUNG_DDR3_1866_512M'; did you mean 'SAMSUNG_DDR3L_1866_512M'?
mosys-1.2.3-r854:         case SAMSUNG_DDR3_1866_512M:
mosys-1.2.3-r854:              ^~~~~~~~~~~~~~~~~~~~~~
mosys-1.2.3-r854:              SAMSUNG_DDR3L_1866_512M
mosys-1.2.3-r854: ../mosys-1.2.3/platform/mistral/memory.c:52:2: note: 'SAMSUNG_DDR3L_1866_512M' declared here
mosys-1.2.3-r854:         SAMSUNG_DDR3L_1866_512M,
mosys-1.2.3-r854:         ^
mosys-1.2.3-r854: 2 errors generated.



Original change's description:
> mosys: Support mistral
> 
> Read memory config from VPD.
> 
> BUG=b:116760505
> TEST=build mosys and run on mistral
> 
> Change-Id: Ifcc7af1fd5e4b459f9b69fa23741194a3f4d331e
> Reviewed-on: https://chromium-review.googlesource.com/c/1284993
> Reviewed-by: Zhihong Yu <zhihongyu@chromium.org>
> Commit-Queue: Zheng Pan <zhengpan@chromium.org>
> Tested-by: Zheng Pan <zhengpan@chromium.org>

Bug: b:116760505
Change-Id: I0e3c732bafb69aa9302acb3aca0e39405abf3e4e
Reviewed-on: https://chromium-review.googlesource.com/c/1446335
Reviewed-by: Garrick Evans <garrick@chromium.org>
Reviewed-by: Shuo-Peng Liao <deanliao@google.com>
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Shuo-Peng Liao <deanliao@google.com>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>
Trybot-Ready: Daniel Kurtz <djkurtz@chromium.org>